version: '3.8'

networks:
  hyperion_webapp:
    name: nginx_network
    external: true

services:
  hyperion_webapp:
    container_name: hyperion_webapp
    image: borodindmitriy/hyperion-webapp:${GITHUB_SHA}
    restart: always
    networks:
      - hyperion_webapp
    healthcheck:
      test: ['CMD', 'curl', '-k', '-f', 'http://127.0.0.1:3000/']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
